/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 blender.gltf 
*/

import React, { useRef } from "react";
import { shaderMaterial, useGLTF } from "@react-three/drei";
import glsl from "glslify";
import { extend } from "@react-three/fiber";
const CardShaderMaterial = shaderMaterial(
  {
    opacity: 1.0,
  },

  glsl`
      varying vec3 vPosition;

      void main() {
        vPosition = position;
        gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
      } 
  `,
  glsl`
    varying vec3 vPosition;

    void main() {
      float opacity = -vPosition.y * 0.5 + 0.3;
      gl_FragColor = vec4(0.238, 0.162, 0.325, opacity);
    } 
  `
);
extend({ CardShaderMaterial });
export function Blender(props) {
  const { nodes, materials } = useGLTF("/models/blender.gltf");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0, 0.263, 0.197]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={10.292}
      >
        <mesh
          geometry={nodes.kitchenBlender_1.geometry}
          material={materials.metalMedium}
        />
        <mesh
          geometry={nodes.kitchenBlender_2.geometry}
          material={materials.metal}
        />
        <mesh
          geometry={nodes.kitchenBlender_3.geometry}
          material={materials.glass}
        />
      </group>
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials["Material.002"]}
        scale={[1.791, 2.499, 0.1]}
      />
      <mesh geometry={nodes.Cube001.geometry} scale={[1.735, 2.42, 0.1]}>
        <cardShaderMaterial transparent />
      </mesh>
      <mesh
        geometry={nodes.Text.geometry}
        material={materials["Material.001"]}
        position={[0, -0.779, 0.165]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.38}
      />
      <mesh
        geometry={nodes.Text001.geometry}
        material={materials["Material.001"]}
        position={[0, -1.22, 0.165]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.242}
      />
      <mesh
        geometry={nodes.Text002.geometry}
        material={materials["Material.001"]}
        position={[0, -1.602, 0.165]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.145}
      />
      <mesh
        geometry={nodes.Circle.geometry}
        material={materials["star Material"]}
        position={[-0.667, -1.9, 0.116]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.157}
      />
      <mesh
        geometry={nodes.Circle001.geometry}
        material={materials["star Material"]}
        position={[-0.333, -1.9, 0.116]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.157}
      />
      <mesh
        geometry={nodes.Circle002.geometry}
        material={materials["star Material"]}
        position={[0, -1.9, 0.123]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.157}
      />
      <mesh
        geometry={nodes.Circle003.geometry}
        material={materials["star Material"]}
        position={[0.333, -1.9, 0.116]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.157}
      />
      <mesh
        geometry={nodes.Circle004.geometry}
        material={materials["star Material"]}
        position={[0.667, -1.9, 0.116]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.157}
      />
    </group>
  );
}

useGLTF.preload("/blender.gltf");
