/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 face_proj_3.gltf 
*/

import React, { useEffect, useRef, useState } from "react";
import { useGLTF, OrthographicCamera } from "@react-three/drei";

export function FaceProj(props) {
  const [mouseX, setMouseX] = useState(0);
  const [mouseY, setMouseY] = useState(0);
  useEffect(() => {
    document.addEventListener("mousemove", (e) => {
      setMouseX(
        ((e.clientX - window.innerWidth / 2) * 150) / window.innerWidth
      );
      setMouseY(
        ((e.clientY - window.innerHeight / 2) * 150) / window.innerHeight
      );
    });
  }, []);
  const { nodes, materials } = useGLTF("/models/face_proj_3.gltf");
  return (
    <group
      dispose={null}
      scale={0.17}
      rotation={[mouseY / 1000, mouseX / 1000, 0]}
    >
      {/* <axesHelper args={[10]} /> */}
      <group scale={0.01} position={[0, -9, 0]}>
        <group position={[-17.638, 1070.655, -75.818]}>
          <mesh
            geometry={nodes.Sphere_12.geometry}
            material={nodes.Sphere_12.material}
            position={[486.293, 146.789, 744.977]}
            rotation={[-1.023, 0, 0]}
            scale={0.65}
          />
          <mesh
            geometry={nodes.Sphere_12_1.geometry}
            material={nodes.Sphere_12_1.material}
            position={[269.038, -139.8, 192.484]}
            rotation={[-1.023, 0, 0]}
            scale={1.493}
          />
          <mesh
            geometry={nodes.Sphere_12_2.geometry}
            material={nodes.Sphere_12_2.material}
            position={[416.556, 301.909, 718.068]}
            rotation={[-1.917, 0, 0]}
            scale={1.338}
          />
          <mesh
            geometry={nodes.Sphere_10.geometry}
            material={nodes.Sphere_10.material}
            position={[229.523, 369.747, 268.63]}
            rotation={[-1.023, 0, 0]}
            scale={0.94}
          />
          <mesh
            geometry={nodes.Sphere_10_1.geometry}
            material={nodes.Sphere_10_1.material}
            position={[349.253, 487.93, 633.183]}
            rotation={[-1.023, 0, 0]}
            scale={0.842}
          />
          <mesh
            geometry={nodes.Sphere_10_2.geometry}
            material={nodes.Sphere_10_2.material}
            position={[156.459, 411.466, 968.913]}
            rotation={[-1.023, 0, 0]}
            scale={0.65}
          />
          <mesh
            geometry={nodes.Sphere_10_3.geometry}
            material={nodes.Sphere_10_3.material}
            position={[-26.625, 479.889, 903.44]}
            rotation={[-1.023, 0, 0]}
            scale={1.493}
          />
          <mesh
            geometry={nodes.Sphere_9.geometry}
            material={nodes.Sphere_9.material}
            position={[114.237, 28.915, 43.535]}
            rotation={[-Math.PI / 2, 1.392, 0]}
            scale={1.325}
          />
          <mesh
            geometry={nodes.Sphere_9_1.geometry}
            material={nodes.Sphere_9_1.material}
            position={[178.987, -255.543, 86.353]}
            rotation={[-Math.PI / 2, 1.392, 0]}
          />
          <mesh
            geometry={nodes.Sphere_9_2.geometry}
            material={nodes.Sphere_9_2.material}
            position={[-73.678, -441.835, 209.099]}
            rotation={[-Math.PI / 2, 1.392, 0]}
            scale={1.744}
          />
          <mesh
            geometry={nodes.Sphere_9_3.geometry}
            material={nodes.Sphere_9_3.material}
            position={[-279.866, -551.281, 355.177]}
            rotation={[-Math.PI / 2, 1.392, 0]}
            scale={1.103}
          />
          <mesh
            geometry={nodes.Sphere_9_4.geometry}
            material={nodes.Sphere_9_4.material}
            position={[466.118, -310.365, 546.574]}
            rotation={[-0.031, 0.172, -1.39]}
            scale={0.65}
          />
          <mesh
            geometry={nodes.Sphere_9_5.geometry}
            material={nodes.Sphere_9_5.material}
            position={[-264.38, -382.826, 235.598]}
            rotation={[-Math.PI / 2, 1.392, 0]}
            scale={1.493}
          />
          <mesh
            geometry={nodes.Sphere_9_6.geometry}
            material={nodes.Sphere_9_6.material}
            position={[-128.9, 26.958, 49.361]}
            rotation={[-Math.PI / 2, 1.392, 0]}
            scale={1.216}
          />
          <mesh
            geometry={nodes.Sphere_9_7.geometry}
            material={nodes.Sphere_9_7.material}
            position={[-331.485, 71.369, 158.807]}
            rotation={[-2.147, 1.417, 0.539]}
          />
          <mesh
            geometry={nodes.Sphere_9_8.geometry}
            material={nodes.Sphere_9_8.material}
            position={[217.589, -389.125, 168.684]}
            rotation={[-Math.PI / 2, 1.392, 0]}
          />
          <mesh
            geometry={nodes.Sphere_9_9.geometry}
            material={nodes.Sphere_9_9.material}
            position={[-393.717, -48.668, 311.903]}
            rotation={[-Math.PI / 2, 1.392, 0]}
            scale={1.649}
          />
          <mesh
            geometry={nodes.Sphere_9_10.geometry}
            material={nodes.Sphere_9_10.material}
            position={[286.714, -524.727, 370.748]}
            rotation={[-Math.PI / 2, 1.392, 0]}
            scale={1.376}
          />
          <mesh
            geometry={nodes.Sphere_9_11.geometry}
            material={nodes.Sphere_9_11.material}
            position={[27.699, -647.653, 327.227]}
            rotation={[-Math.PI / 2, 1.392, -0.001]}
            scale={0.898}
          />
          <mesh
            geometry={nodes.Sphere_9_12.geometry}
            material={nodes.Sphere_9_12.material}
            position={[-286.535, -605.716, 474.048]}
            rotation={[-Math.PI / 2, 1.392, 0]}
            scale={0.898}
          />
          <mesh
            geometry={nodes.Sphere_9_13.geometry}
            material={nodes.Sphere_9_13.material}
            position={[-422.52, 465.292, 719.743]}
            rotation={[-Math.PI / 2, 1.392, 0]}
            scale={0.65}
          />
          <mesh
            geometry={nodes.Sphere_9_14.geometry}
            material={nodes.Sphere_9_14.material}
            position={[-217.909, -159.001, 154.863]}
            rotation={[-Math.PI / 2, 1.392, 0]}
            scale={1.493}
          />
          <mesh
            geometry={nodes.Sphere_9_15.geometry}
            material={nodes.Sphere_9_15.material}
            position={[-496.57, -68.943, 538.309]}
            rotation={[-Math.PI / 2, 1.392, 0]}
          />
          <mesh
            geometry={nodes.Sphere_9_16.geometry}
            material={nodes.Sphere_9_16.material}
            position={[-118.143, -622.9, 388.509]}
            rotation={[-Math.PI / 2, 1.392, 0]}
          />
          <mesh
            geometry={nodes.Sphere_9_17.geometry}
            material={nodes.Sphere_9_17.material}
            position={[-432.584, -230.495, 481.075]}
            rotation={[-Math.PI / 2, 1.392, 0]}
            scale={1.649}
          />
          <mesh
            geometry={nodes.Sphere_9_18.geometry}
            material={nodes.Sphere_9_18.material}
            position={[-493.054, 56.023, 788.679]}
            rotation={[-Math.PI / 2, 1.392, 0]}
            scale={0.65}
          />
          <mesh
            geometry={nodes.Sphere_9_19.geometry}
            material={nodes.Sphere_9_19.material}
            position={[-409.375, -396.636, 426.606]}
            rotation={[-Math.PI / 2, 1.392, 0]}
            scale={1.493}
          />
          <mesh
            geometry={nodes.Sphere_9_20.geometry}
            material={nodes.Sphere_9_20.material}
            position={[173.287, -613.043, 451.026]}
            rotation={[-Math.PI / 2, 1.392, 0]}
            scale={1.158}
          />
          <mesh
            geometry={nodes.Sphere_9_21.geometry}
            material={nodes.Sphere_9_21.material}
            position={[151.952, -477.729, 294.073]}
            rotation={[-Math.PI / 2, 1.392, 0.11]}
            scale={1.493}
          />
          <mesh
            geometry={nodes.Sphere_9_22.geometry}
            material={nodes.Sphere_9_22.material}
            position={[21.408, -180.214, 65.604]}
            rotation={[-Math.PI / 2, 1.392, 0]}
            scale={1.338}
          />
          <mesh
            geometry={nodes.Sphere_8.geometry}
            material={nodes.Sphere_8.material}
            position={[-13.125, 454.077, 384.767]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1.649}
          />
          <mesh
            geometry={nodes.Sphere_8_1.geometry}
            material={nodes.Sphere_8_1.material}
            position={[-360.74, 339.687, 544.28]}
            rotation={[-1.71, 0.156, -0.011]}
            scale={1.493}
          />
          <mesh
            geometry={nodes.Sphere_8_2.geometry}
            material={nodes.Sphere_8_2.material}
            position={[336.291, 350.332, 471.963]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1.679}
          />
          <mesh
            geometry={nodes.Sphere_7.geometry}
            material={nodes.Sphere_7.material}
            position={[40.87, 254.246, 223.683]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1.649}
          />
          <mesh
            geometry={nodes.Sphere_7_1.geometry}
            material={nodes.Sphere_7_1.material}
            position={[246.568, 426.068, 813.525]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1.493}
          />
          <mesh
            geometry={nodes.Sphere_6.geometry}
            material={nodes.Sphere_6.material}
            position={[-267.125, 387.595, 388.74]}
            rotation={[-0.399, 0, 0]}
            scale={[1, 1, 0.879]}
          />
          <mesh
            geometry={nodes.Sphere_6_1.geometry}
            material={nodes.Sphere_6_1.material}
            position={[-335.027, 422.736, 841.692]}
            rotation={[-0.399, 0.002, 0]}
            scale={[1.649, 1.649, 1.449]}
          />
          <mesh
            geometry={nodes.Sphere_6_2.geometry}
            material={nodes.Sphere_6_2.material}
            position={[-58.11, 544.465, 721.986]}
            rotation={[-0.399, 0, 0]}
            scale={[1.493, 1.493, 1.312]}
          />
          <mesh
            geometry={nodes.Sphere_5.geometry}
            material={nodes.Sphere_5.material}
            position={[411.806, 78.454, 566.04]}
            rotation={[-1.636, 1.195, 0.061]}
            scale={1.649}
          />
          <mesh
            geometry={nodes.Sphere_5_1.geometry}
            material={nodes.Sphere_5_1.material}
            position={[375.831, -347.184, 336.117]}
            rotation={[-1.636, 1.195, 0.061]}
            scale={1.493}
          />
          <mesh
            geometry={nodes.Sphere_5_2.geometry}
            material={nodes.Sphere_5_2.material}
            position={[-111.862, 541.659, 558.872]}
            rotation={[-1.636, 1.195, 0.061]}
            scale={1.338}
          />
          <mesh
            geometry={nodes.Sphere_4.geometry}
            material={nodes.Sphere_4.material}
            position={[-252.585, 244.451, 299.328]}
            rotation={[-Math.PI / 2, 1.277, 0]}
            scale={1.649}
          />
          <mesh
            geometry={nodes.Sphere_3.geometry}
            material={nodes.Sphere_3.material}
            position={[408.565, -155.062, 420.791]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1.649}
          />
          <mesh
            geometry={nodes.Sphere_3_1.geometry}
            material={nodes.Sphere_3_1.material}
            position={[266.275, 124.338, 265.278]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1.493}
          />
          <mesh
            geometry={nodes.Sphere_3_2.geometry}
            material={nodes.Sphere_3_2.material}
            position={[182.91, 518.88, 598.083]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1.338}
          />
          <mesh
            geometry={nodes.Sphere_2.geometry}
            material={nodes.Sphere_2.material}
            position={[-110.352, 184.824, 65.451]}
            rotation={[3.109, -0.036, -Math.PI]}
          />
          <mesh
            geometry={nodes.Sphere_2_1.geometry}
            material={nodes.Sphere_2_1.material}
            position={[-240.674, 447.448, 740.795]}
            rotation={[3.109, -0.036, -Math.PI]}
            scale={1.649}
          />
          <mesh
            geometry={nodes.Sphere_2_2.geometry}
            material={nodes.Sphere_2_2.material}
            position={[-527.196, 78.624, 670.472]}
            rotation={[3.109, -0.036, -Math.PI]}
            scale={0.967}
          />
          <mesh
            geometry={nodes.Sphere_2_3.geometry}
            material={nodes.Sphere_2_3.material}
            position={[-464.533, 99.536, 489.793]}
            rotation={[3.109, -0.036, -Math.PI]}
            scale={1.493}
          />
          <mesh
            geometry={nodes.Sphere_2_4.geometry}
            material={nodes.Sphere_2_4.material}
            position={[-454.372, 261.668, 765.979]}
            rotation={[2.509, 0.282, 2.986]}
            scale={1.338}
          />
        </group>
        <group position={[-35.363, 852.806, 547.936]}>
          <mesh
            geometry={nodes.nose.geometry}
            material={nodes.nose.material}
            position={[3.12 + mouseX / 5, -127.554 - mouseY / 5, 534.965]}
          />
          <mesh
            geometry={nodes.ear_r.geometry}
            material={nodes.ear_r.material}
            position={[544.199, -1.318, 20.731]}
            scale={[1, 1.133, 1]}
          />
          <mesh
            geometry={nodes.ear_l.geometry}
            material={nodes.ear_l.material}
            position={[-544.199, -1.318, 16.192]}
            scale={[-1, 1.133, 1]}
          />
          <mesh
            geometry={nodes.face.geometry}
            material={nodes.face.material}
            position={[14.413, 80.262, 48.175]}
          />
        </group>
        <group position={[204.903, 992.362, 998.549]} scale={[-1, 1, 1]}>
          <group
            position={[-2.883, -98.597, 7.92]}
            rotation={[0, -Math.PI / 9, 0]}
          >
            <mesh
              geometry={nodes.Cube_7.geometry}
              material={nodes.Cube_7.material}
              position={[42.577 - mouseX, 33.229 - mouseY, 87.259]}
            />
            <mesh
              geometry={nodes.Cube_5.geometry}
              material={nodes.Cube_5.material}
              position={[0 - mouseX / 5, 0 - mouseY / 5, 31.567]}
            />
          </group>
          <mesh
            geometry={nodes.brow_r.geometry}
            material={nodes.brow_r.material}
            position={[22.567, -28.232 - mouseY / 3, 5.295]}
            rotation={[0.032, -0.355, -0.424]}
          />
        </group>
        <group position={[-269.44, 992.362, 998.549]}>
          <group
            position={[-2.883, -98.597, 7.92]}
            rotation={[0, -Math.PI / 9, 0]}
          >
            <mesh
              geometry={nodes.Cube_7_1.geometry}
              material={nodes.Cube_7_1.material}
              position={[42.577 + mouseX, 33.229 - mouseY, 87.259]}
            />
            <mesh
              geometry={nodes.Cube_5_1.geometry}
              material={nodes.Cube_5_1.material}
              position={[0 + mouseX / 5, 0 - mouseY / 5, 31.567]}
            />
          </group>
          <mesh
            geometry={nodes.Torus.geometry}
            material={nodes.Torus.material}
            position={[22.567, -28.232 - mouseY / 3, 5.295]}
            rotation={[0.032, -0.355, -0.424]}
          />
        </group>
        <directionalLight
          intensity={0.638}
          decay={2}
          rotation={[-0.301, 0.576, 0.518]}
        />
        <directionalLight
          intensity={0.7}
          decay={2}
          rotation={[-0.506, 0.629, 0.756]}
        />
        <OrthographicCamera
          makeDefault={false}
          far={100000}
          near={0}
          position={[598.328, 105.807, 1862.201]}
          rotation={[-0.02, 0.028, 0.001]}
        />
        <mesh
          geometry={nodes.mouth.geometry}
          material={nodes.mouth.material}
          position={[-31.353, 508.374, 1054.644]}
          rotation={[0.14, 0, 0]}
          scale={[1 - Math.abs(mouseX) / 100, 1 + mouseY / 170, 1]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/face_proj_3.gltf");
