/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 heart2.glb 
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/heart2.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="f6bcb81c5d674405b84df409a29b9a55fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="BASE_HEART"
                  position={[-0.676, 38.876, -0.255]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <group name="Object_5" position={[-0.09, 0, -38.876]}>
                    <mesh
                      name="BASE_HEART_Material_#41_0"
                      geometry={nodes["BASE_HEART_Material_#41_0"].geometry}
                      material={materials.Material_41}
                      position={[0.079, 0, 40.278]}
                    />
                    <mesh
                      name="BASE_HEART_Material_#41_0001"
                      geometry={nodes["BASE_HEART_Material_#41_0001"].geometry}
                      material={materials.changeittotrans}
                      position={[0.079, 0, 40.278]}
                      scale={1.138}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/heart2.glb");
