/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 lastHopeGlobe.gltf 
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";

export function Globeasd(props) {
  const { nodes, materials } = useGLTF("/models/lastHopeGlobe.gltf");
  return (
    <group {...props} dispose={null} scale={10}>
      <PerspectiveCamera
        makeDefault={true}
        far={1000}
        near={0.001}
        fov={22.895}
        position={[0, 0, 2.212]}
      />
      <mesh
        geometry={nodes.frame.geometry}
        material={materials["instances grid.001"]}
        scale={0.305}
      >
        <mesh scale={0.99}>
          <sphereGeometry args={[1, 64, 64]} />
          <meshStandardMaterial color="white" />
        </mesh>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane355.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane355_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane337.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane337_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane236.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane236_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane332.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane332_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane369.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane369_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane352.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane352_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane368.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane368_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane208.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane208_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane354.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane354_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane213.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane213_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane201.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane201_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane204.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane204_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane203.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane203_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane212.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane212_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane217.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane217_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane223.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane223_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane310.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane310_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane365.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane365_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane364.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane364_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane238.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane238_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane257.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane257_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane247.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane247_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane260.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane260_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane349.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane349_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane320.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane320_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane353.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane353_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane331.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane331_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane317.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane317_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane343.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane343_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane230.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane230_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane225.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane225_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane229.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane229_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane220.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane220_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane219.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane219_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane218.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane218_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane221.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane221_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane222.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane222_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane269.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane269_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane315.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane315_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane515.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane515_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane209.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane209_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane210.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane210_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane205.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane205_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane265.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane265_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane359.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane359_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane206.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane206_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane262.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane262_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane252.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane252_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane248.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane248_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane237.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane237_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane207.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane207_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane242.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane242_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane239.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane239_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane246.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane246_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane241.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane241_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane240.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane240_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane243.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane243_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane250.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane250_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane351.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane351_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane226.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane226_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane233.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane233_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane234.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane234_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane334.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane334_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane211.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane211_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane224.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane224_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane231.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane231_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane232.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane232_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane235.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane235_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane249.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane249_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane251.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane251_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane256.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane256_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane261.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane261_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane263.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane263_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane313.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane313_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane350.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane350_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane339.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane339_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane245.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane245_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane366.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane366_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane514.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane514_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane329.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane329_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane254.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane254_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane259.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane259_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane255.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane255_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane244.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane244_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane264.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane264_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane348.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane348_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane266.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane266_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane215.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane215_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane202.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane202_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane216.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane216_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane228.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane228_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane227.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane227_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane214.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane214_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane029.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane029_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane360.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane360_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane258.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane258_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
        <group position={[-0.015, 0.051, 1.077]} scale={-3.412}>
          <mesh
            geometry={nodes.Plane253.geometry}
            material={materials["material.001"]}
          />
          <mesh
            geometry={nodes.Plane253_1.geometry}
            material={materials.OutlineMaterial}
          />
        </group>
      </mesh>
    </group>
  );
}

useGLTF.preload("/lastHopeGlobe.gltf");
