/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 trial1.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Trial(props) {
  const { nodes, materials } = useGLTF("/models/trial1.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Sphere.geometry}
        material={materials["Material.001"]}
        position={[0, 4.615, 0]}
      />
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials["Material.002"]}
        position={[-3.498, 4.615, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[3.393, 1, 3.393]}
      />
    </group>
  );
}

useGLTF.preload("/trial1.glb");
